INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (1, 'Camp Nou', "C. d'Arístides Maillol, 12", 50000, 10, 5);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (2, 'Old Trafford', 'Sir Matt Busby Way, Stretford', 40000, 8, 18);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (3, 'Santiago Bernabeu', 'Madrid, Španija', 35000, 6, 25);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (4, 'San Siro', 'Av. de Concha Espina, 1', 81044, 9, 15);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (5, 'Allianz Arena', 'Werner-Heisenberg-Allee 25', 75024, 11, 20);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (6, 'Wembley Stadium', 'London HA9 0WS', 90000, 7, 1);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (7, 'Signal Iduna Park', 'Strobelallee 50', 81365, 5, 20);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (8, 'Emirates Stadium', 'Hornsey Rd, London N7 7AJ', 60704, 8, 1);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (9, 'Anfield', 'Anfield Rd, Anfield, Liverpool L4 0TH', 54000, 9, 24);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (10, 'Stadio Olimpico', 'Viale dei Gladiatori, 00135', 72698, 6, 4);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (11, 'Parc des Princes', '24 Rue du Commandant Guilbaud, 75016', 48583, 10, 2);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (12, 'Estadio da Luz', 'Av. Eusébio da Silva Ferreira, 1500-313', 65000, 7, 13);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (13, 'Johan Cruijff Arena', 'Johan Cruijff Boulevard 1, 1101 AX', 55885, 8, 7);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (14, 'Stade de France', '93200 Saint-Denis', 80000, 12, 2);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (15, 'Estadio do Dragao', 'Via Futebol Clube do Porto, 4350-415', 50033, 5, 23);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (16, 'Estadio Olímpico', 'Dimitriou Vikela Avenue 52. Halandri', 75000, 8, 6);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (17, 'Türk Telekom Stadyumu', 'Huzur Mh., Metin Oktay Caddesi, 34386', 52600, 10, 21);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (18, 'Veltins-Arena', 'Rudi-Assauer-Platz 1, 45891 Gelsenkirchen', 62271, 7, 20);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (19, 'Stadio San Paolo', 'Napoli, Italija', 40000, 8, 16);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (20, 'JNA', 'Stadion Partizana, Humska 1, Beograd 11000', 29775, 9, 11);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (21, 'Stanford Bridge', 'Fulham Rd., London SW6 1HS', 40341, 6, 1);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (22, 'Vande Metropolitano', 'Av. de Luis Aragonés, 4, 28022', 68456, 7, 25);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (23, 'Moscow Stadium', 'Luzhniki Street, 24, Moscow', 81000, 10, 17);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (24, 'Mestallia', 'Av. de Suècia, s/n, 46010 València', 49430, 7, 19);
INSERT INTO Stadion (StadionID, Naziv, Adresa, Kapacitet, BrojUlaza, GradID) VALUES (25, 'Guissepe Meatsa', 'Piazzale Angelo Moratti, 20151 Milano', 75817, 8,15);