INSERT INTO Drzave (DrzavaID, Naziv) VALUES (1, 'Srbija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (2, 'Hrvatska');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (3, 'Slovenija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (4, 'Bosna i Hercegovina');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (5, 'Crna Gora');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (6, 'Makedonija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (7, 'Austrija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (8, 'Italija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (9, 'Nemačka');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (10, 'Francuska');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (11, 'Španija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (12, 'Portugal');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (13, 'Holandija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (14, 'Belgija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (15, 'Švajcarska');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (16, 'Poljska');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (17, 'Češka');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (18, 'Slovačka');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (19, 'Mađarska');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (20, 'Grčka');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (21, 'Turska');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (22, 'Rusija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (23, 'Velika Britanija');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (24, 'SAD');
INSERT INTO Drzave (DrzavaID, Naziv) VALUES (25, 'Kanada');